// <auto-generated />
using System;
using MediaDock.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaDock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MediaDockDbContext))]
    partial class MediaDockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string[]>("ExcludedCountries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("excluded_countries")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("ExcludedGenres")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("excluded_genres")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<long>("MinImdbVotes")
                        .HasColumnType("bigint")
                        .HasColumnName("min_imdb_votes");

                    b.Property<decimal>("MinMovieRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("min_movie_rating");

                    b.Property<decimal>("MinSeriesRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("min_series_rating");

                    b.Property<string>("OmdbApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("omdb_api_key");

                    b.Property<int>("OmdbDailyRequestLimit")
                        .HasColumnType("integer")
                        .HasColumnName("omdb_daily_request_limit");

                    b.Property<int>("OscarEnrichmentMaxFilmsPerRun")
                        .HasColumnType("integer")
                        .HasColumnName("oscar_enrichment_max_films_per_run");

                    b.Property<int>("OscarEnrichmentMaxRequestsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("oscar_enrichment_max_requests_per_day");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_min_imdb_votes", "min_imdb_votes BETWEEN 0 AND 1000000000");

                            t.HasCheckConstraint("ck_settings_min_movie_rating", "min_movie_rating BETWEEN 0 AND 10");

                            t.HasCheckConstraint("ck_settings_min_series_rating", "min_series_rating BETWEEN 0 AND 10");

                            t.HasCheckConstraint("ck_settings_omdb_daily_request_limit", "omdb_daily_request_limit >= 0");

                            t.HasCheckConstraint("ck_settings_oscar_max_films_per_run", "oscar_enrichment_max_films_per_run BETWEEN 0 AND 100000");

                            t.HasCheckConstraint("ck_settings_oscar_max_requests_per_day", "oscar_enrichment_max_requests_per_day >= 0");

                            t.HasCheckConstraint("ck_settings_singleton_id", "id = 1");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.BackgroundJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrentSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("current_source");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_stage");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<byte[]>("InputBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("input_bytes");

                    b.Property<string>("InputContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_content_type");

                    b.Property<string>("InputFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("input_file_name");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("job_type");

                    b.Property<DateTimeOffset?>("ProgressUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("progress_updated_at");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_summary");

                    b.Property<long?>("ScanRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("scan_run_id");

                    b.Property<DateTimeOffset?>("ScheduledSlotUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_slot_utc");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_background_jobs");

                    b.HasIndex("JobType", "ux_background_jobs_active_rss_scan")
                        .IsUnique()
                        .HasDatabaseName("ux_background_jobs_active_rss_scan")
                        .HasFilter("job_type = 'rss_scan' AND status IN ('queued', 'running')");

                    b.HasIndex("JobType", "ux_background_jobs_active_oscar_enrichment")
                        .IsUnique()
                        .HasDatabaseName("ux_background_jobs_active_oscar_enrichment")
                        .HasFilter("job_type = 'oscar_enrichment' AND status IN ('queued', 'running')");

                    b.HasIndex("ScanRunId")
                        .IsUnique()
                        .HasDatabaseName("ux_background_jobs_scan_run_id")
                        .HasFilter("scan_run_id IS NOT NULL");

                    b.HasIndex("ScheduledSlotUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_background_jobs_scheduled_slot_utc")
                        .HasFilter("scheduled_slot_utc IS NOT NULL");

                    b.HasIndex("Status", "EnqueuedAt")
                        .HasDatabaseName("ix_background_jobs_status_enqueued_at");

                    b.ToTable("background_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_background_jobs_input_type", "(job_type = 'oscar_import' AND (input_bytes IS NOT NULL OR status IN ('succeeded', 'partial', 'failed'))) OR (job_type IN ('rss_scan', 'oscar_enrichment') AND input_bytes IS NULL)");

                            t.HasCheckConstraint("ck_background_jobs_lifecycle", "(status = 'queued' AND started_at IS NULL AND finished_at IS NULL) OR (status = 'running' AND started_at IS NOT NULL AND finished_at IS NULL) OR (status IN ('succeeded', 'partial', 'failed') AND started_at IS NOT NULL AND finished_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_background_jobs_status", "status IN ('queued', 'running', 'succeeded', 'partial', 'failed')");

                            t.HasCheckConstraint("ck_background_jobs_trigger", "trigger IN ('manual', 'schedule')");

                            t.HasCheckConstraint("ck_background_jobs_type", "job_type IN ('rss_scan', 'oscar_import', 'oscar_enrichment')");

                            t.HasCheckConstraint("ck_background_jobs_type_trigger", "(job_type = 'rss_scan' AND trigger IN ('manual', 'schedule')) OR (job_type IN ('oscar_import', 'oscar_enrichment') AND trigger = 'manual')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.BackgroundJobEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_code");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_background_job_events");

                    b.HasIndex("JobId", "Id")
                        .HasDatabaseName("ix_background_job_events_job_id_id");

                    b.ToTable("background_job_events", (string)null);
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.BackgroundSchedulerState", b =>
                {
                    b.Property<string>("ScheduleName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schedule_name");

                    b.Property<DateTimeOffset>("LastEvaluatedSlotUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_slot_utc");

                    b.HasKey("ScheduleName")
                        .HasName("pk_background_scheduler_state");

                    b.ToTable("background_scheduler_state", (string)null);
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.FavoriteMovie", b =>
                {
                    b.Property<long>("TitleId")
                        .HasColumnType("bigint")
                        .HasColumnName("title_id");

                    b.Property<bool>("AddedFromCatalog")
                        .HasColumnType("boolean")
                        .HasColumnName("added_from_catalog");

                    b.Property<bool>("AddedFromOscar")
                        .HasColumnType("boolean")
                        .HasColumnName("added_from_oscar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ToDownload")
                        .HasColumnType("boolean")
                        .HasColumnName("to_download");

                    b.Property<bool>("ToWatch")
                        .HasColumnType("boolean")
                        .HasColumnName("to_watch");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TitleId")
                        .HasName("pk_favorite_movies");

                    b.ToTable("favorite_movies", null, t =>
                        {
                            t.HasCheckConstraint("ck_favorite_movies_origin", "added_from_oscar OR added_from_catalog");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.MetadataCacheEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cache_key");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("LookupIdentity")
                        .HasColumnType("text")
                        .HasColumnName("lookup_identity");

                    b.Property<string>("LookupTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lookup_title");

                    b.Property<int?>("LookupYear")
                        .HasColumnType("integer")
                        .HasColumnName("lookup_year");

                    b.Property<string>("LookupYearSemantics")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lookup_year_semantics");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_metadata_cache");

                    b.HasAlternateKey("CacheKey")
                        .HasName("ak_metadata_cache_cache_key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_metadata_cache_expires_at");

                    b.ToTable("metadata_cache", null, t =>
                        {
                            t.HasCheckConstraint("ck_metadata_cache_expiry", "expires_at > fetched_at");

                            t.HasCheckConstraint("ck_metadata_cache_status", "status IN ('found', 'confirmed_not_found')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.Occurrence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FeedEntryId")
                        .HasColumnType("text")
                        .HasColumnName("feed_entry_id");

                    b.Property<string>("FeedType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("feed_type");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Quality")
                        .HasColumnType("text")
                        .HasColumnName("quality");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_title");

                    b.Property<string>("RipType")
                        .HasColumnType("text")
                        .HasColumnName("rip_type");

                    b.Property<string>("SourceFeedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_feed_name");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceItemKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_item_key");

                    b.Property<DateTimeOffset?>("SourcePublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_published_at");

                    b.Property<long>("TitleId")
                        .HasColumnType("bigint")
                        .HasColumnName("title_id");

                    b.Property<string>("TorrentUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("torrent_url");

                    b.HasKey("Id")
                        .HasName("pk_occurrences");

                    b.HasAlternateKey("SourceId", "SourceItemKey")
                        .HasName("ak_occurrences_source_id_source_item_key");

                    b.HasIndex("TitleId", "LastSeenAt")
                        .HasDatabaseName("ix_occurrences_title_id_last_seen_at");

                    b.ToTable("occurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_occurrences_seen_range", "first_seen_at <= last_seen_at");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OmdbDailyUsage", b =>
                {
                    b.Property<DateOnly>("UtcDate")
                        .HasColumnType("date")
                        .HasColumnName("utc_date");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<bool>("DailyRequestLimitReached")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("daily_request_limit_reached");

                    b.Property<int>("OscarRequests")
                        .HasColumnType("integer")
                        .HasColumnName("oscar_requests");

                    b.Property<bool>("ProviderQuotaExceeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("provider_quota_exceeded");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("integer")
                        .HasColumnName("total_requests");

                    b.HasKey("UtcDate")
                        .HasName("pk_omdb_daily_usage");

                    b.ToTable("omdb_daily_usage", null, t =>
                        {
                            t.HasCheckConstraint("ck_omdb_daily_usage_counts", "total_requests >= 0 AND oscar_requests >= 0 AND oscar_requests <= total_requests");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OscarEnrichmentRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CacheHits")
                        .HasColumnType("integer")
                        .HasColumnName("cache_hits");

                    b.Property<int>("EligibleFilms")
                        .HasColumnType("integer")
                        .HasColumnName("eligible_films");

                    b.Property<int>("EnrichedFilms")
                        .HasColumnType("integer")
                        .HasColumnName("enriched_films");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("HttpAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("http_attempts");

                    b.Property<int>("NotFoundFilms")
                        .HasColumnType("integer")
                        .HasColumnName("not_found_films");

                    b.Property<int>("ProcessedFilms")
                        .HasColumnType("integer")
                        .HasColumnName("processed_films");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TemporaryErrors")
                        .HasColumnType("integer")
                        .HasColumnName("temporary_errors");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_oscar_enrichment_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_oscar_enrichment_runs_started_at");

                    b.ToTable("oscar_enrichment_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_oscar_enrichment_runs_counts", "eligible_films >= 0 AND processed_films >= 0 AND enriched_films >= 0 AND not_found_films >= 0 AND temporary_errors >= 0 AND cache_hits >= 0 AND http_attempts >= 0");

                            t.HasCheckConstraint("ck_oscar_enrichment_runs_finish_time", "(status = 'running' AND finished_at IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_oscar_enrichment_runs_status", "status IN ('running', 'succeeded', 'partial', 'quota_stopped', 'failed', 'cancelled')");

                            t.HasCheckConstraint("ck_oscar_enrichment_runs_trigger", "trigger IN ('manual', 'schedule')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OscarFilm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EnrichmentAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("enrichment_attempt_count");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("pending")
                        .HasColumnName("enrichment_status");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("film_title");

                    b.Property<int>("FilmYear")
                        .HasColumnType("integer")
                        .HasColumnName("film_year");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("imdb_id");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<DateTimeOffset?>("LastEnrichmentAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_enrichment_attempt_at");

                    b.Property<string>("LastEnrichmentError")
                        .HasColumnType("text")
                        .HasColumnName("last_enrichment_error");

                    b.Property<DateTimeOffset?>("NextEnrichmentAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_enrichment_attempt_at");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_title");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stable_key");

                    b.Property<long>("TitleId")
                        .HasColumnType("bigint")
                        .HasColumnName("title_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_oscar_films");

                    b.HasIndex("FilmYear")
                        .HasDatabaseName("ix_oscar_films_film_year");

                    b.HasIndex("StableKey")
                        .IsUnique()
                        .HasDatabaseName("ux_oscar_films_stable_key");

                    b.HasIndex("TitleId");

                    b.ToTable("oscar_films", null, t =>
                        {
                            t.HasCheckConstraint("ck_oscar_films_enrichment_attempt_count", "enrichment_attempt_count >= 0");

                            t.HasCheckConstraint("ck_oscar_films_enrichment_status", "enrichment_status IN ('pending', 'enriched', 'not_found', 'temporary_error')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OscarNomination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_category");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("Ceremony")
                        .HasColumnType("integer")
                        .HasColumnName("ceremony");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("ImportKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("import_key");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_winner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NomineeIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nominee_ids");

                    b.Property<string>("Nominees")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nominees");

                    b.Property<long>("OscarFilmId")
                        .HasColumnType("bigint")
                        .HasColumnName("oscar_film_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_oscar_nominations");

                    b.HasIndex("ImportKey")
                        .IsUnique()
                        .HasDatabaseName("ux_oscar_nominations_import_key");

                    b.HasIndex("OscarFilmId");

                    b.HasIndex("CanonicalCategory", "Ceremony")
                        .HasDatabaseName("ix_oscar_nominations_category_ceremony");

                    b.ToTable("oscar_nominations", (string)null);
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.ParseLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Decision")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("EventKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("event_kind");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_name");

                    b.Property<string>("FeedType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("feed_type");

                    b.Property<string>("IgnoreReason")
                        .HasColumnType("text")
                        .HasColumnName("ignore_reason");

                    b.Property<bool>("Ignored")
                        .HasColumnType("boolean")
                        .HasColumnName("ignored");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("OmdbStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("omdb_status");

                    b.Property<bool>("ParsedSuccessfully")
                        .HasColumnType("boolean")
                        .HasColumnName("parsed_successfully");

                    b.Property<string>("ParsedTitle")
                        .HasColumnType("text")
                        .HasColumnName("parsed_title");

                    b.Property<int?>("ParsedYear")
                        .HasColumnType("integer")
                        .HasColumnName("parsed_year");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_title");

                    b.Property<string>("RetryState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("retry_state");

                    b.Property<long?>("ScanRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("scan_run_id");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceItemKey")
                        .HasColumnType("text")
                        .HasColumnName("source_item_key");

                    b.Property<DateTimeOffset?>("SourcePublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_published_at");

                    b.HasKey("Id")
                        .HasName("pk_parse_logs");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_parse_logs_processed_at");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("IX_parse_logs_source_id");

                    b.ToTable("parse_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_parse_logs_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_parse_logs_retry_state", "retry_state IN ('retryable', 'terminal', 'resolved')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.RssItemProcessingState", b =>
                {
                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceItemKey")
                        .HasColumnType("text")
                        .HasColumnName("source_item_key");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("disposition");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SourceId", "SourceItemKey")
                        .HasName("pk_rss_item_states");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_rss_item_states_expires_at");

                    b.ToTable("rss_item_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_rss_item_states_disposition", "disposition IN ('resolved', 'terminal')");

                            t.HasCheckConstraint("ck_rss_item_states_expiry", "disposition = 'resolved' OR (disposition = 'terminal' AND expires_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.ScanRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CacheHits")
                        .HasColumnType("integer")
                        .HasColumnName("cache_hits");

                    b.Property<int>("EntriesSeen")
                        .HasColumnType("integer")
                        .HasColumnName("entries_seen");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.PrimitiveCollection<string[]>("ErrorSummary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("error_summary")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<int>("FeedsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("feeds_processed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("IgnoredEntries")
                        .HasColumnType("integer")
                        .HasColumnName("ignored_entries");

                    b.Property<int>("KnownEntriesSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("known_entries_skipped");

                    b.Property<int>("OccurrencesCreated")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_created");

                    b.Property<int>("OmdbRequests")
                        .HasColumnType("integer")
                        .HasColumnName("omdb_requests");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TitlesCreated")
                        .HasColumnType("integer")
                        .HasColumnName("titles_created");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_scan_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_scan_runs_started_at");

                    b.ToTable("scan_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scan_runs_finish_time", "(status = 'running' AND finished_at IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_scan_runs_status", "status IN ('running', 'succeeded', 'partial', 'failed')");

                            t.HasCheckConstraint("ck_scan_runs_trigger", "trigger IN ('schedule', 'manual', 'local')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FeedType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("feed_type");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stable_key");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasAlternateKey("StableKey")
                        .HasName("ak_sources_stable_key");

                    b.ToTable("sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_sources_feed_type", "feed_type IN ('movie', 'series_complete', 'series_ongoing')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.Title", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Awards")
                        .HasColumnType("text")
                        .HasColumnName("awards");

                    b.Property<string>("BoxOffice")
                        .HasColumnType("text")
                        .HasColumnName("box_office");

                    b.Property<int?>("BroadcastRangeEndYear")
                        .HasColumnType("integer")
                        .HasColumnName("broadcast_range_end_year");

                    b.Property<string>("BroadcastRangeRaw")
                        .HasColumnType("text")
                        .HasColumnName("broadcast_range_raw");

                    b.Property<int?>("BroadcastRangeStartYear")
                        .HasColumnType("integer")
                        .HasColumnName("broadcast_range_start_year");

                    b.Property<string>("ContentKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("content_kind");

                    b.PrimitiveCollection<string[]>("Countries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("countries")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Director")
                        .HasColumnType("text")
                        .HasColumnName("director");

                    b.Property<DateTimeOffset?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("genres")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("imdb_id");

                    b.Property<decimal?>("ImdbRating")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("imdb_rating");

                    b.Property<long?>("ImdbVotes")
                        .HasColumnType("bigint")
                        .HasColumnName("imdb_votes");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("media_type");

                    b.Property<decimal?>("Metascore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("metascore");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_title");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<string>("Runtime")
                        .HasColumnType("text")
                        .HasColumnName("runtime");

                    b.Property<string>("SourceType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_type");

                    b.Property<string>("TitleText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_titles");

                    b.HasIndex("ImdbId")
                        .IsUnique()
                        .HasDatabaseName("ux_titles_imdb_id")
                        .HasFilter("imdb_id IS NOT NULL AND btrim(imdb_id) <> ''");

                    b.HasIndex("NormalizedTitle", "Year", "MediaType")
                        .HasDatabaseName("ix_titles_normalized_title_year_media_type");

                    b.ToTable("titles", null, t =>
                        {
                            t.HasCheckConstraint("ck_titles_content_kind", "content_kind IS NULL OR content_kind IN ('standard', 'documentary', 'short')");

                            t.HasCheckConstraint("ck_titles_media_type", "media_type IN ('movie', 'series', 'documentary', 'short')");

                            t.HasCheckConstraint("ck_titles_seen_range", "(first_seen_at IS NULL AND last_seen_at IS NULL) OR (first_seen_at IS NOT NULL AND last_seen_at IS NOT NULL AND first_seen_at <= last_seen_at)");

                            t.HasCheckConstraint("ck_titles_source_type", "source_type IS NULL OR source_type IN ('movie', 'series')");
                        });
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.BackgroundJob", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.ScanRun", "ScanRun")
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_background_jobs_scan_runs_scan_run_id");

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.BackgroundJobEvent", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.BackgroundJob", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_background_job_events_background_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.FavoriteMovie", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_movies_titles_title_id");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.Occurrence", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.Source", "Source")
                        .WithMany("Occurrences")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_occurrences_sources_source_id");

                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.Title", "Title")
                        .WithMany("Occurrences")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_occurrences_titles_title_id");

                    b.Navigation("Source");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OscarFilm", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oscar_films_titles_title_id");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OscarNomination", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.OscarFilm", "OscarFilm")
                        .WithMany("Nominations")
                        .HasForeignKey("OscarFilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_oscar_nominations_films_oscar_film_id");

                    b.Navigation("OscarFilm");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.ParseLog", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.ScanRun", null)
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parse_logs_scan_runs_scan_run_id");

                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.Source", "Source")
                        .WithMany("ParseLogs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parse_logs_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.RssItemProcessingState", b =>
                {
                    b.HasOne("MediaDock.Infrastructure.Persistence.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rss_item_states_sources_source_id");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.BackgroundJob", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.OscarFilm", b =>
                {
                    b.Navigation("Nominations");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.Source", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("ParseLogs");
                });

            modelBuilder.Entity("MediaDock.Infrastructure.Persistence.Entities.Title", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
